CREATE TABLE IF NOT EXISTS USER (
  USER_ID VARCHAR(15) NOT NULL,
  USER_PASSWD VARCHAR(100) NOT NULL,
  CONSTRAINT USER_PK PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS KEYWORD (
  KEYWORD VARCHAR(100) NOT NULL,
  USER_ID VARCHAR(15) NOT NULL,
  SEARCH_COUNT NUMBER NOT NULL,
  UPDATE_TIME TIMESTAMP NOT NULL,
  CONSTRAINT KEYWORD_PK PRIMARY KEY (KEYWORD, USER_ID)
);